### ISSUE TITLE
main.py problem

### ISSUE THREAD

**Issue by mufengR** [abdullahtarek/football_analysis#5]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\football_analize\main.py", line 85, in <module>
    main()
  File "C:\Users\Administrator\Desktop\football_analize\main.py", line 26, in main
    camera_movement_estimator = CameraMovementEstimator(video_frames[0])
                                                        ~~~~~~~~~~~~^^^
IndexError: list index out of range
Finally, running main.py reported this error, please ask me why and how to modifiy it.

**Comment by yoyo920** [comment]
Hi,
Did you find the solution to the problem ?

**Comment by mufengR** [comment]
Yes！



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 28, 2024 15:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [abdullahtarek/football_analysis] main.py problem (Issue #5)




 
Hi,
 Did you find the solution to the problem ?

**Comment by yoyo920** [comment]
I would appreciate it if you could share your solution with me.

**Comment by KrishiaOlan** [comment]
> Yes！
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Jul 28, 2024 15:35 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [abdullahtarek/football_analysis] main.py problem (Issue #5) Hi, Did you find the solution to the problem ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

hi, how to resolve the issue?

**Comment by Manoj-Kumar22** [comment]
![issue](https://github.com/user-attachments/assets/7d93c48a-ff57-4fdd-a795-2a8a17a9bb94)
guys help how to solve it????

**Comment by thobeu** [comment]
> > Yes！
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Sun, Jul 28, 2024 15:35 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [abdullahtarek/football_analysis] main.py problem (Issue #5) Hi, Did you find the solution to the problem ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> hi, how to resolve the issue?

Did you adjust the video name in the main.py (https://github.com/abdullahtarek/football_analysis/blob/main/main.py#L14) for your video?

**Comment by Fakhriemir07** [comment]
> Yes！
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Jul 28, 2024 15:35 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [abdullahtarek/football_analysis] main.py problem (Issue #5) Hi, Did you find the solution to the problem ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hei, i got the same problem, how do you fix it?
