### ISSUE TITLE
When i tried with new sample video,it shows errors

### ISSUE THREAD

**Issue by Heinhtettkyaw** [abdullahtarek/football_analysis#7]
Traceback (most recent call last):
  File "d:\football_analysis-main\main.py", line 87, in <module>
    main()
  File "d:\football_analysis-main\main.py", line 51, in main
    team = team_assigner.get_player_team(video_frames[frame_num],
                                         ~~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range

**Comment by Fakhriemir07** [comment]
Same issue here, have you been able to fix it?

**Comment by huongnguthe** [comment]
cuz the code is made only for the given vid

**Comment by kendalf1** [comment]
1.Make sure the main.py is referencing your new video name
2. Delete the 2 pkl files in Stubs folder
-It will have to recreate these and it will take some time.

I have had success with short (8-30 second videos) in 1080P 25FPS mp4 format.
